title: Minimal theme
# logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
#### Phantom Navigation menu
enable_nav: true
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/cv', text: 'CV' }

### Phantom settings
admin_name: 'Sanjay Seetharaman'
google_analytics: "UA-164910723-1" # Update with your own tracking ID

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chiefsan.github.io/minimal" # the base hostname & protocol for your site, e.g. https://example.com
